### ISSUE TITLE
Research Dashboard/API

### ISSUE THREAD

**Issue by JB-Tellez** [code-commando/api#1]
As a developer I want to research the Canvas API to determine it's feasibility.

Done When: We have some answers to these questions...
- [ ] How does their API work?
- [ ] What can we get for free (public API?)
- [ ] Can we look into any class and get a list of names?
- [ ] Do we need to be authorized?  Can we use an eternal OAuth provider?

**Comment by khuynh92** [comment]
1. How does their API work?
GET requests work by entering a URL to a api endpoint (e.g. https://canvas.instructure.com/api/v1/courses/:courseID/students). To access a particular courses information, you need to either be a student/teacher to acess information.

https://canvas.instructure.com/api/v1/courses/:courseID/permissions shows what permissions you have with that course

response is a JSON object??

2. Access to course information, students, and more depending on course status(e.g. student, teacher).

3. You must be a part of that course to view a class roster.

4. Still Unsure
