### ISSUE TITLE
CODE RUNNER: Electron integration

### ISSUE THREAD

**Issue by ambergkim** [code-commando/api#25]
As a developer I need to know if my app can be run with Electron so that I can have a desktop app.

**Comment by jozue06** [comment]
Hey Amber, Issue #23 and #24 are in progress. We are using monaco editor for the front end that is a better option than code mirror, as well as runs smoothly in a browser/electron. we have setup a demo.html in the repl directory of the api, as well as added a model. we will use this to send data to our compiler, the NPM package NEL. NEL will return with a promise back to our route where we can then display the results in the DOM.

**Comment by mrebb** [comment]
Electron integration is up and running for the code that we have. Electron also worked for the previous API that we discontinued because it was a 3rd party API.
