### ISSUE TITLE
CODE RUNNER: Stretch - Code Monaco Editor

### ISSUE THREAD

**Issue by ambergkim** [code-commando/api#26]
As a developer I need to know if my app can be run with Electron so that I can have a desktop app.

**Comment by mrebb** [comment]
Hi Amber, we have changed our code editor from code mirror to Monaco editor. And we deployed it with electron and it is up and running. We are as of now connecting the dots between sending the raw code from Monaco editor to npm package NEL to compile and send back the result to front end. We will update as we progress further hopefully something before Saturday morning.

**Comment by jozue06** [comment]
Hi Amber, we have connected the dots between Monaco, our demo.html and our NEL runner. We are now working on github integration for CRUD.
