### ISSUE TITLE
Research README Slide Show

### ISSUE THREAD

**Issue by johncokos** [code-commando/api#3]
As a developer I would like some options for converting a .md file from GitHub into an HTML slideshow.

Notes:  Evaluate a few libraries
- [x] https://remarkjs.com/#1
- [ ] https://www.npmjs.com/package/markdown-to-slides
- [ ] https://www.npmjs.com/package/swipeshow
- [ ] https://github.com/hakimel/reveal.js

Done when
- [ ] We have a good handle on the best approach to feed the UI the markup or JSON that it needs
- [ ] We have a good handle on how a stable, usable README.md file needs to be formatted

**Comment by stariel** [comment]
We read up on the suggested packages along with a couple others that convert a markdown to a JSON object. After reviewing the features and requirements we determined that remark.js would probably be the best option for a few reasons:
1. It is simple to use and renders the slides in the browser
2. It doesn't require using very much html or strange markdown rules to format slides - the README files will still be easily readable by humans as the slide designations are unobtrusive.
3. It has a feature for code blocks that uses syntax highlighting for JavaScript and Python.

**Comment by JB-Tellez** [comment]
Here are 3 sample README files to build out **simple** prototype. Feel free to make your own copies and edit/deploy them as needed.
https://github.com/codefellows/seattle-javascript-401n5/tree/master/14-relationship-modeling
https://github.com/codefellows/seattle-javascript-401n5/tree/master/15-trees
https://github.com/codefellows/seattle-javascript-401n5/tree/master/16-basic-authentication
