### ISSUE TITLE
Research: Random Student and Pears 

### ISSUE THREAD

**Issue by johncokos** [code-commando/api#4]
As a developer, I would like to know my options on implementing random student selector and pears so  that I can create the proper API.

Notes:
 - Evaluate existing solutions (Ariel has done a similar thing in 201, Nick Caragan has done a pears thing for the TAs)
- Design the DB Schema (which would store the data if we didn't have Canvas)

Done When:
- [ ] We have a path for implementing the right api data to the front-end
- [ ] We have a schema identified for storing the class and student information in Mongo to serve as both starting point and fallback (in case canvas fails)

**Comment by Lennerblom** [comment]
- [x] the path is GET canvas.instructure.com/api/v1/courses/{course_id}/students
- [x] Aaron wrote up a schema with user_id, name, course
- [x] located a random picker 3rd party npm package (pick-random) unless we write our own
