### ISSUE TITLE
Research: Quiz Generator

### ISSUE THREAD

**Issue by johncokos** [code-commando/api#5]
As a developer, I would like to have a pathway to CRUD for the quizzes feature so that I can begin development.

Done When:
- [ ] Decide on the data Format to store quizzes (JSON, YaML, etc)
- [ ] Research algorithms to let us alter the weight of questions, configurations, etc.

**Comment by Bolstad09** [comment]
[X] Using JSON for now and will think about using YaML down the road if we can do a little more research
[X] Using mLab for our database
- https://mlab.com/databases/quiz-generator
[X] Using the database to determine what questions have stronger pull.
[X] https://www.npmjs.com/package/javascript-quiz-using-json
